apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader
  namespace: audit-workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downloader
  template:
    metadata:
      labels:
        app: downloader
    spec:
      containers:
      - name: downloader
        image: downloader:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "debug"
        - name: MINIO_ENDPOINT
          value: "host.k3d.internal:9000"
        - name: MINIO_USE_SSL
          value: "false"
        envFrom:
        - secretRef:
            name: worker-config
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "50m"

---
apiVersion: v1
kind: Service
metadata:
  name: downloader
  namespace: audit-workers
spec:
  selector:
    app: downloader
  ports:
  - port: 8080
    targetPort: 8080
